#! /bin/sh
# findcore
# Find core dumps (including from Valgrind)
# (c) Reuben Thomas <rrt@sc3d.org> 5/4/2006, 2/2/2007, 4/4/2011, 30/9/11
# This program is in the public domain

locate -0er "/\(vg\)\?core\(\.\[0-9\]\+\)\?$" | xargs -0 ls -ld | grep -v ^[dl]
