#!/usr/bin/perl
# my
# Find files matching a pattern under the user's home directory
# Colour the output if stdout is a tty
# Needs GNU grep
# (c) Reuben Thomas <rrt@sc3d.org> 2013-2019
# This program is in the public domain.

# FIXME: Write a launcher that does something like: my $pattern | tee >(head -3 | xargs -d '\n' xdg-open)
# and split out the colorization into a wrapper that works for both that and my.

use 5.10.0;

use strict;
use warnings;

# Get regexp to search for
my $pattern = pop || "";

# Get location of database
my $xdg_cache_dir = `xdg-cache-dir`;
chomp $xdg_cache_dir;
my $database = "$xdg_cache_dir/locate.db.txt";

# Grep database
open(my $cmd, '-|', "grep", "--text", "--color=auto", @ARGV, $pattern, $database) or die $!;

# Display only files that exist
while (<$cmd>) {
  chomp $_;
  say $_ if -e $_;
}
