#!/bin/bash
# Run a program with modified environment
# (c) Reuben Thomas 2014-2021
# Released under the GPL version 3, or (at your option) any later version.

# FIXME: add --wrapper=COMMAND that will be prepended to the command invocation
if [ $# -lt 1 ]; then
cat <<EOF
Usage: rerun [ENVIRONMENT] PROGRAM-PATH [ARGUMENT...]

rerun allows a program to be run with a modified environment or arguments,
without changing the way it is invoked. It allows the modified program and
original program to be on the PATH, and works with session management.
PROGRAM-PATH must be the full path to the invoking script; a typical
invocation is:

  exec rerun FOO=bar \$0 "\$@"
EOF
exit 1
fi

if [[ "$1" == *=* ]]; then
    environment="$1"
    shift
fi
program="$1"
shift

# Find real program
path_remove ()  {
    export PATH=$(echo -n $PATH | awk -v RS=: -v ORS=: '$0 != "'$1'"' | sed 's/:$//')
}

old_PATH="$PATH"
path_remove $(dirname $program)
real_program=$(which $(basename $program))
if [[ "$?" != 0 ]]; then
    echo Could not find program $program
    exit 1
fi
export PATH="$old_PATH"

# Execute program with environment and modified $0
if test -n "$environment"; then
    export $environment
fi
exec -a $real_program $real_program "$@"
