#!/usr/bin/env python3
# zcat
# cat possibly compressed files
# (c) Reuben Thomas   19/10/06-16/8/16 (Perl); 18th August 2025 (Python)
# Distributed under the GNU General Public License version 3, or (at
# your option) any later version. There is no warranty.


# Depends on: acat (atool)
# FIXME: Accept basic command-line options including --

import os
import re
import subprocess
import sys
from pathlib import Path


name = Path(sys.argv[0]).name

def isCompressed(file: os.PathLike):
    mimetype = subprocess.check_output(
        ["file", "--mime", "--brief", "--uncompress", "--dereference", "--", str(file)],
        text=True,
    )
    return re.search(" compressed-encoding=", mimetype)

if len(sys.argv) > 0:
    for file in sys.argv[1:]:
        cat_cmd = "acat" if isCompressed(file) else "cat"
        subprocess.check_call([cat_cmd, "--", file])
else:
    print(f"Usage: {name} FILE...", file=sys.stderr)
    exit(1)
